
# Custom MegaLinter Flavor: my-test-flavor
FROM alpine:3.18

# Add basic dependencies
RUN apk add --no-cache bash

# Copy entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
