{
 "title": "DASH - ML Errors & Elapse",
 "tags": [ "megalinter" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gitIdentifier",
    "label": "Repo / Branch",
    "query": {}
   },
   {
    "name": "linterKey",
    "label": "Linter",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$linterKey", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "linterKey" },
  {
   "title": "Latest errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{source=\"MegaLinter\", linterKey=\"$linterKey\", gitIdentifier=\"$gitIdentifier\"}",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Number of errors found",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "linter_run_numberErrorsFound{source=\"MegaLinter\", linterKey=\"$linterKey\", gitIdentifier=\"$gitIdentifier\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{source=\"MegaLinter\", linterKey=\"$linterKey\", gitIdentifier=\"$gitIdentifier\"}",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Elapsed time by MegaLinter run",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "linter_run_elapsedTime{source=\"MegaLinter\", linterKey=\"$linterKey\", gitIdentifier=\"$gitIdentifier\"}"
    }
   ]
  },
  {
   "title": "Average Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "linter_run_elapsedTime{source=\"MegaLinter\", linterKey=\"$linterKey\", gitIdentifier=\"$gitIdentifier\"}"
    }
   ]
  },
  {
   "title": "Latest run",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{source=\"MegaLinter\", linterKey=\"$linterKey\", gitIdentifier=\"$gitIdentifier\"}",
     "maxLines": 1
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{gitIdentifier=\"$gitIdentifier\", linterKey=\"$linterKey\"} |= ``",
     "maxLines": 1
    }
   ]
  }
 ]
}