#!/usr/bin/env python3
"""
Vendor the betterleaks secret-detection ruleset used to mask secrets in linter
outputs (see megalinter/logger.py).

Only rule ids and regexes are kept: the masking engine ignores every other
field, and the raw upstream file is ~5x larger. Run from build.py during
documentation builds, or standalone to refresh the file locally.
"""

import logging
import os
import sys
import tomllib

import requests
from megalinter.constants import (
    BETTERLEAKS_RULESET_FILE_NAME,
    BETTERLEAKS_RULESET_REPO,
    BETTERLEAKS_RULESET_VERSION,
)

REPO_HOME = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET_FILE = (
    f"{REPO_HOME}/megalinter/descriptors/additional/{BETTERLEAKS_RULESET_FILE_NAME}"
)
SOURCE_URL = (
    f"https://raw.githubusercontent.com/{BETTERLEAKS_RULESET_REPO}/"
    f"{BETTERLEAKS_RULESET_VERSION}/config/betterleaks.toml"
)
# The upstream ruleset has 400+ rules. A much smaller result means a truncated
# or restructured file: keeping the previous ruleset is safer than shipping a
# ruleset that would silently stop masking most secrets.
MIN_EXPECTED_RULES = 300


def render_ruleset(rules) -> str:
    lines = [
        f"# Minified from {SOURCE_URL}",
        "# Generated by .automation/vendor_betterleaks_ruleset.py - do not edit manually.",
        "# betterleaks is MIT licensed - Copyright (c) 2026 Zachary Rice",
        "",
    ]
    for rule in rules:
        lines += [
            "[[rules]]",
            f'id = "{rule["id"]}"',
            f"regex = '''{rule['regex']}'''",
            "",
        ]
    return "\n".join(lines)


def vendor() -> bool:
    logging.info(f"Vendoring betterleaks ruleset from {SOURCE_URL}")
    try:
        response = requests.get(SOURCE_URL, timeout=30)
    except Exception as e:
        logging.warning(
            f"Could not fetch betterleaks ruleset, keeping current file: {e}"
        )
        return False
    if response.status_code != 200:
        logging.warning(
            "Could not fetch betterleaks ruleset "
            f"(HTTP {response.status_code}), keeping current file"
        )
        return False

    try:
        upstream_config = tomllib.loads(response.text)
    except tomllib.TOMLDecodeError as e:
        logging.warning(
            f"betterleaks ruleset is not valid TOML, keeping current file: {e}"
        )
        return False

    rules = [
        rule
        for rule in upstream_config.get("rules", [])
        if rule.get("id") and rule.get("regex")
    ]
    if len(rules) < MIN_EXPECTED_RULES:
        logging.warning(
            f"betterleaks ruleset has only {len(rules)} usable rules "
            f"(expected at least {MIN_EXPECTED_RULES}), keeping current file"
        )
        return False
    if not any(rule["id"] == "generic-api-key" for rule in rules):
        logging.warning(
            "betterleaks ruleset does not contain the generic-api-key rule, "
            "keeping current file"
        )
        return False

    content = render_ruleset(rules)
    if os.path.isfile(TARGET_FILE):
        with open(TARGET_FILE, "r", encoding="utf-8") as previous_file:
            if previous_file.read() == content:
                logging.info(f"betterleaks ruleset is up to date ({len(rules)} rules)")
                return False

    with open(TARGET_FILE, "w", encoding="utf-8") as target_file:
        target_file.write(content)
    logging.info(
        f"Updated {BETTERLEAKS_RULESET_FILE_NAME} from "
        f"{BETTERLEAKS_RULESET_VERSION} ({len(rules)} rules)"
    )
    return True


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s: %(message)s",
        handlers=[logging.StreamHandler(sys.stdout)],
    )
    vendor()
