# !/usr/bin/env python3
"""
Unit tests for ACTION linter zizmor
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class action_zizmor_test(TestCase, LinterTestRoot):
    descriptor_id = "ACTION"
    linter_name = "zizmor"
