# !/usr/bin/env python3
"""
Unit tests for ACTION linter actionlint
This class has been automatically @generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.helpers import utilstest
from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class action_actionlint_test(TestCase, LinterTestRoot):
    descriptor_id = "ACTION"
    linter_name = "actionlint"

    def test_include_success(self):
        utilstest.linter_test_setup(
            {
                "additional_test_variables": {
                    "ACTION_FILTER_REGEX_INCLUDE": "^actionlint_"
                }
            }
        )
        utilstest.test_linter_success(self.get_linter_instance(), self)

    def test_include_failure(self):
        utilstest.linter_test_setup(
            {
                "additional_test_variables": {
                    "ACTION_FILTER_REGEX_INCLUDE": "^actionlint_"
                }
            }
        )
        utilstest.test_linter_failure(self.get_linter_instance(), self)

    def test_exclude_success(self):
        utilstest.linter_test_setup(
            {
                "additional_test_variables": {
                    "ACTION_FILTER_REGEX_EXCLUDE": "/actionlint_"
                }
            }
        )
        utilstest.test_linter_success(self.get_linter_instance(), self)

    def test_exclude_failure(self):
        utilstest.linter_test_setup(
            {
                "additional_test_variables": {
                    "ACTION_FILTER_REGEX_EXCLUDE": "/actionlint_"
                }
            }
        )
        utilstest.test_linter_failure(self.get_linter_instance(), self)
