# !/usr/bin/env python3
"""
Unit tests for ANSIBLE linter ansible-lint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class ansible_ansible_lint_test(TestCase, LinterTestRoot):
    descriptor_id = "ANSIBLE"
    linter_name = "ansible-lint"
