# !/usr/bin/env python3
"""
Unit tests for ARM linter arm-ttk
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class arm_arm_ttk_test(TestCase, LinterTestRoot):
    descriptor_id = "ARM"
    linter_name = "arm-ttk"
