# !/usr/bin/env python3
"""
Unit tests for ARM linter bicep
This class has been automatically @generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class arm_bicep_test(TestCase, LinterTestRoot):
    descriptor_id = "ARM"
    linter_name = "bicep"
