# !/usr/bin/env python3
"""
Unit tests for BASH linter bash-exec
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class bash_bash_exec_test(TestCase, LinterTestRoot):
    descriptor_id = "BASH"
    linter_name = "bash-exec"
