# !/usr/bin/env python3
"""
Unit tests for BASH linter shfmt
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class bash_shfmt_test(TestCase, LinterTestRoot):
    descriptor_id = "BASH"
    linter_name = "shfmt"
