# !/usr/bin/env python3
"""
Unit tests for BICEP linter bicep_linter
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class bicep_bicep_linter_test(TestCase, LinterTestRoot):
    descriptor_id = "BICEP"
    linter_name = "bicep_linter"
