# !/usr/bin/env python3
"""
Unit tests for C linter clang-format
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class c_clang_format_test(TestCase, LinterTestRoot):
    descriptor_id = "C"
    linter_name = "clang-format"
