# !/usr/bin/env python3
"""
Unit tests for CLOJURE linter cljstyle
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class clojure_cljstyle_test(TestCase, LinterTestRoot):
    descriptor_id = "CLOJURE"
    linter_name = "cljstyle"
