# !/usr/bin/env python3
"""
Unit tests for COFFEE linter coffeelint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class coffee_coffeelint_test(TestCase, LinterTestRoot):
    descriptor_id = "COFFEE"
    linter_name = "coffeelint"
