# !/usr/bin/env python3
"""
Unit tests for COPYPASTE linter jscpd
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class copypaste_jscpd_test(TestCase, LinterTestRoot):
    descriptor_id = "COPYPASTE"
    linter_name = "jscpd"
