# !/usr/bin/env python3
"""
Unit tests for CPP linter oclint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class cpp_oclint_test(TestCase, LinterTestRoot):
    descriptor_id = 'CPP'
    linter_name = 'oclint'
