# !/usr/bin/env python3
"""
Unit tests for CPP linter cppcheck
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class cpp_cppcheck_test(TestCase, LinterTestRoot):
    descriptor_id = "CPP"
    linter_name = "cppcheck"
