# !/usr/bin/env python3
"""
Unit tests for CSHARP linter roslynator
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class csharp_roslynator_test(TestCase, LinterTestRoot):
    descriptor_id = "CSHARP"
    linter_name = "roslynator"
