# !/usr/bin/env python3
"""
Unit tests for CSHARP linter dotnet-format
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class csharp_dotnet_format_test(TestCase, LinterTestRoot):
    descriptor_id = "CSHARP"
    linter_name = "dotnet-format"
