# !/usr/bin/env python3
"""
Unit tests for CSS linter scss-lint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class css_scss_lint_test(TestCase, LinterTestRoot):
    descriptor_id = "CSS"
    linter_name = "scss-lint"
