# !/usr/bin/env python3
"""
Unit tests for EDITORCONFIG linter editorconfig-checker
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class editorconfig_editorconfig_checker_test(TestCase, LinterTestRoot):
    descriptor_id = "EDITORCONFIG"
    linter_name = "editorconfig-checker"
