# !/usr/bin/env python3
"""
Unit tests for ERLANG linter elvis
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class erlang_elvis_test(TestCase, LinterTestRoot):
    descriptor_id = 'ERLANG'
    linter_name = 'elvis'
