# !/usr/bin/env python3
"""
Unit tests for FISH linter fish_indent
This class has been automatically @generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class fish_fish_indent_test(TestCase, LinterTestRoot):
    descriptor_id = "FISH"
    linter_name = "fish_indent"
