# !/usr/bin/env python3
"""
Unit tests for GIT linter git_diff
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class git_git_diff_test(TestCase, LinterTestRoot):
    descriptor_id = "GIT"
    linter_name = "git_diff"
