# !/usr/bin/env python3
"""
Unit tests for GO linter revive
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class go_revive_test(TestCase, LinterTestRoot):
    descriptor_id = "GO"
    linter_name = "revive"
