# !/usr/bin/env python3
"""
Unit tests for GRAPHQL linter biome
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class graphql_biome_test(TestCase, LinterTestRoot):
    descriptor_id = "GRAPHQL"
    linter_name = "biome"
