# !/usr/bin/env python3
"""
Unit tests for GRAPHQL linter graphql-schema-linter
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class graphql_graphql_schema_linter_test(TestCase, LinterTestRoot):
    descriptor_id = "GRAPHQL"
    linter_name = "graphql-schema-linter"
