# !/usr/bin/env python3
"""
Unit tests for GROOVY linter npm-groovy-lint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class groovy_npm_groovy_lint_test(TestCase, LinterTestRoot):
    descriptor_id = "GROOVY"
    linter_name = "npm-groovy-lint"
