# !/usr/bin/env python3
"""
Unit tests for HTML linter djlint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class html_djlint_test(TestCase, LinterTestRoot):
    descriptor_id = "HTML"
    linter_name = "djlint"
