# !/usr/bin/env python3
"""
Unit tests for JAVA linter checkstyle
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class java_checkstyle_test(TestCase, LinterTestRoot):
    descriptor_id = "JAVA"
    linter_name = "checkstyle"
