# !/usr/bin/env python3
"""
Unit tests for JAVASCRIPT linter putout
This class has been automatically @generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class javascript_putout_test(TestCase, LinterTestRoot):
    descriptor_id = "JAVASCRIPT"
    linter_name = "putout"
