# !/usr/bin/env python3
"""
Unit tests for JSON linter prettier
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class json_prettier_test(TestCase, LinterTestRoot):
    descriptor_id = "JSON"
    linter_name = "prettier"
