# !/usr/bin/env python3
"""
Unit tests for JSON linter npm-package-json-lint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class json_npm_package_json_lint_test(TestCase, LinterTestRoot):
    descriptor_id = "JSON"
    linter_name = "npm-package-json-lint"
