# !/usr/bin/env python3
"""
Unit tests for JSX linter eslint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class jsx_eslint_test(TestCase, LinterTestRoot):
    descriptor_id = "JSX"
    linter_name = "eslint"
