# !/usr/bin/env python3
"""
Unit tests for KOTLIN linter ktlint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class kotlin_ktlint_test(TestCase, LinterTestRoot):
    descriptor_id = "KOTLIN"
    linter_name = "ktlint"
