# !/usr/bin/env python3
"""
Unit tests for LATEX linter chktex
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class latex_chktex_test(TestCase, LinterTestRoot):
    descriptor_id = "LATEX"
    linter_name = "chktex"
