# !/usr/bin/env python3
"""
Unit tests for LOGSTASH linter mustache
This class has been automatically @generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class logstash_mustache_test(TestCase, LinterTestRoot):
    descriptor_id = "LOGSTASH"
    linter_name = "mustache"
