# !/usr/bin/env python3
"""
Unit tests for MAKEFILE linter checkmake
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class makefile_checkmake_test(TestCase, LinterTestRoot):
    descriptor_id = "MAKEFILE"
    linter_name = "checkmake"
