# !/usr/bin/env python3
"""
Unit tests for MARKDOWN linter remark-lint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class markdown_remark_lint_test(TestCase, LinterTestRoot):
    descriptor_id = "MARKDOWN"
    linter_name = "remark-lint"
