# !/usr/bin/env python3
"""
Unit tests for MARKDOWN linter markdown-link-check
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class markdown_markdown_link_check_test(TestCase, LinterTestRoot):
    descriptor_id = "MARKDOWN"
    linter_name = "markdown-link-check"
