# !/usr/bin/env python3
"""
Unit tests for NIX linter nixpkgs-fmt
This class has been automatically @generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class nix_nixpkgs_fmt_test(TestCase, LinterTestRoot):
    descriptor_id = "NIX"
    linter_name = "nixpkgs-fmt"
