# !/usr/bin/env python3
"""
Unit tests for PERL linter perlcritic
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class perl_perlcritic_test(TestCase, LinterTestRoot):
    descriptor_id = "PERL"
    linter_name = "perlcritic"
