# !/usr/bin/env python3
"""
Unit tests for PHP linter php-cs-fixer
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class php_phpcsfixer_test(TestCase, LinterTestRoot):
    descriptor_id = "PHP"
    linter_name = "php-cs-fixer"
