# !/usr/bin/env python3
"""
Unit tests for PHP linter psalm
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class php_psalm_test(TestCase, LinterTestRoot):
    descriptor_id = "PHP"
    linter_name = "psalm"
