# !/usr/bin/env python3
"""
Unit tests for POWERSHELL linter powershell_formatter
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

import os
import unittest
from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class powershell_powershell_formatter_test(TestCase, LinterTestRoot):
    descriptor_id = "POWERSHELL"
    linter_name = "powershell_formatter"

    def test_success_file_lint_mode(self):
        self.check_if_another_test_suite()
        super().test_success_file_lint_mode()

    def test_success_list_of_files_lint_mode(self):
        self.check_if_another_test_suite()
        super().test_success_list_of_files_lint_mode()

    def test_success_project_lint_mode(self):
        self.check_if_another_test_suite()
        super().test_success_project_lint_mode()

    def test_failure_file_lint_mode(self):
        self.check_if_another_test_suite()
        super().test_failure_file_lint_mode()

    def test_failure_list_of_files_lint_mode(self):
        self.check_if_another_test_suite()
        super().test_failure_list_of_files_lint_mode()

    def test_failure_project_lint_mode(self):
        self.check_if_another_test_suite()
        super().test_failure_project_lint_mode()

    def test_get_linter_version(self):
        self.check_if_another_test_suite()
        super().test_get_linter_version()

    def test_get_linter_help(self):
        self.check_if_another_test_suite()
        super().test_get_linter_help()

    def test_report_tap(self):
        self.check_if_another_test_suite()
        super().test_report_tap()

    def test_report_sarif(self):
        self.check_if_another_test_suite()
        super().test_report_sarif()

    def test_format_fix(self):
        self.check_if_another_test_suite()
        super().test_format_fix()

    def check_if_another_test_suite(self):
        if os.environ.get("SINGLE_LINTER", "") == "POWERSHELL_POWERSHELL":
            raise unittest.SkipTest("Skipped because unrelated test suite")
