# !/usr/bin/env python3
"""
Unit tests for POWERSHELL linter powershell
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class powershell_powershell_test(TestCase, LinterTestRoot):
    descriptor_id = "POWERSHELL"
    linter_name = "powershell"
