# !/usr/bin/env python3
"""
Unit tests for PUPPET linter puppet-lint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class puppet_puppet_lint_test(TestCase, LinterTestRoot):
    descriptor_id = "PUPPET"
    linter_name = "puppet-lint"
