# !/usr/bin/env python3
"""
Unit tests for PYTHON linter ruff-format
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class python_ruff_format_test(TestCase, LinterTestRoot):
    descriptor_id = "PYTHON"
    linter_name = "ruff-format"
