# !/usr/bin/env python3
"""
Unit tests for R linter lintr
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class r_lintr_test(TestCase, LinterTestRoot):
    descriptor_id = "R"
    linter_name = "lintr"
