# !/usr/bin/env python3
"""
Unit tests for RAKU linter raku
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class raku_raku_test(TestCase, LinterTestRoot):
    descriptor_id = "RAKU"
    linter_name = "raku"
