# !/usr/bin/env python3
"""
Unit tests for REPOSITORY linter semgrep
This class has been automatically @generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.helpers import utilstest
from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class repository_semgrep_test(TestCase, LinterTestRoot):
    descriptor_id = "REPOSITORY"
    linter_name = "semgrep"

    def test_security_flavor_success(self):
        utilstest.linter_test_setup(
            {
                "additional_test_variables": {
                    "REPOSITORY_SEMGREP_RULESETS_TYPE": "security"
                }
            }
        )
        utilstest.test_linter_success(self.get_linter_instance(), self)

    def test_security_flavor_failure(self):
        utilstest.linter_test_setup(
            {
                "additional_test_variables": {
                    "REPOSITORY_SEMGREP_RULESETS_TYPE": "security"
                }
            }
        )
        utilstest.test_linter_failure(self.get_linter_instance(), self)
