# !/usr/bin/env python3
"""
Unit tests for REPOSITORY linter goodcheck
This class has been automatically @generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class repository_goodcheck_test(TestCase, LinterTestRoot):
    descriptor_id = "REPOSITORY"
    linter_name = "goodcheck"
