# !/usr/bin/env python3
"""
Unit tests for ROBOTFRAMEWORK linter robocop
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class robotframework_robocop_test(TestCase, LinterTestRoot):
    descriptor_id = "ROBOTFRAMEWORK"
    linter_name = "robocop"
