# !/usr/bin/env python3
"""
Unit tests for RST linter rstcheck
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class rst_rstcheck_test(TestCase, LinterTestRoot):
    descriptor_id = "RST"
    linter_name = "rstcheck"
