# !/usr/bin/env python3
"""
Unit tests for RST linter rst-lint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class rst_rst_lint_test(TestCase, LinterTestRoot):
    descriptor_id = "RST"
    linter_name = "rst-lint"
