# !/usr/bin/env python3
"""
Unit tests for RST linter rstfmt
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class rst_rstfmt_test(TestCase, LinterTestRoot):
    descriptor_id = "RST"
    linter_name = "rstfmt"
