# !/usr/bin/env python3
"""
Unit tests for RUBY linter rubocop
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class ruby_rubocop_test(TestCase, LinterTestRoot):
    descriptor_id = "RUBY"
    linter_name = "rubocop"
