# !/usr/bin/env python3
"""
Unit tests for RUST linter clippy
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class rust_clippy_test(TestCase, LinterTestRoot):
    descriptor_id = "RUST"
    linter_name = "clippy"
