# !/usr/bin/env python3
"""
Unit tests for SALESFORCE linter code-analyzer-apex
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class salesforce_code_analyzer_apex_test(TestCase, LinterTestRoot):
    descriptor_id = "SALESFORCE"
    linter_name = "code-analyzer-apex"
