# !/usr/bin/env python3
"""
Unit tests for SALESFORCE linter sfdx-scanner-apex
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class salesforce_sfdx_scanner_apex_test(TestCase, LinterTestRoot):
    descriptor_id = "SALESFORCE"
    linter_name = "sfdx-scanner-apex"
