# !/usr/bin/env python3
"""
Unit tests for SCALA linter scalafix
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class scala_scalafix_test(TestCase, LinterTestRoot):
    descriptor_id = "SCALA"
    linter_name = "scalafix"
