# !/usr/bin/env python3
"""
Unit tests for SPELL linter cspell
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class spell_cspell_test(TestCase, LinterTestRoot):
    descriptor_id = "SPELL"
    linter_name = "cspell"
