# !/usr/bin/env python3
"""
Unit tests for SQL linter tsqllint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class sql_tsqllint_test(TestCase, LinterTestRoot):
    descriptor_id = "SQL"
    linter_name = "tsqllint"
