# !/usr/bin/env python3
"""
Unit tests for SQL linter sql-lint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class sql_sql_lint_test(TestCase, LinterTestRoot):
    descriptor_id = "SQL"
    linter_name = "sql-lint"
