# !/usr/bin/env python3
"""
Unit tests for SQL linter sqlfluff
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class sql_sqlfluff_test(TestCase, LinterTestRoot):
    descriptor_id = "SQL"
    linter_name = "sqlfluff"
