# !/usr/bin/env python3
"""
Unit tests for SWIFT linter swiftlint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class swift_swiftlint_test(TestCase, LinterTestRoot):
    descriptor_id = "SWIFT"
    linter_name = "swiftlint"
