# !/usr/bin/env python3
"""
Unit tests for TEKTON linter tekton-lint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class tekton_tekton_lint_test(TestCase, LinterTestRoot):
    descriptor_id = "TEKTON"
    linter_name = "tekton-lint"
