# !/usr/bin/env python3
"""
Unit tests for TERRAFORM linter terraform-fmt
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class terraform_terraform_fmt_test(TestCase, LinterTestRoot):
    descriptor_id = "TERRAFORM"
    linter_name = "terraform-fmt"
