# !/usr/bin/env python3
"""
Unit tests for TSX linter eslint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class tsx_eslint_test(TestCase, LinterTestRoot):
    descriptor_id = "TSX"
    linter_name = "eslint"
