# !/usr/bin/env python3
"""
Unit tests for TYPESCRIPT linter ts-standard
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class typescript_standard_test(TestCase, LinterTestRoot):
    descriptor_id = "TYPESCRIPT"
    linter_name = "ts-standard"
