# !/usr/bin/env python3
"""
Unit tests for VBDOTNET linter dotnet-format
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class vbdotnet_dotnet_format_test(TestCase, LinterTestRoot):
    descriptor_id = "VBDOTNET"
    linter_name = "dotnet-format"
