# !/usr/bin/env python3
"""
Unit tests for XML linter xmllint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class xml_xmllint_test(TestCase, LinterTestRoot):
    descriptor_id = "XML"
    linter_name = "xmllint"
