# !/usr/bin/env python3
"""
Unit tests for YAML linter yamllint
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class yaml_yamllint_test(TestCase, LinterTestRoot):
    descriptor_id = "YAML"
    linter_name = "yamllint"
