# !/usr/bin/env python3
"""
Unit tests for YAML linter v8r
This class has been automatically @generated by .automation/build.py, please don't update it manually
"""

from unittest import TestCase

from megalinter.tests.test_megalinter.LinterTestRoot import LinterTestRoot


class yaml_v8r_test(TestCase, LinterTestRoot):
    descriptor_id = "YAML"
    linter_name = "v8r"
