descriptor_id: DOCKERFILE
descriptor_type: tooling_format
descriptor_flavors:
  - all_flavors # Applicable to CI in any language project
  - ci_light
file_names_regex:
  - 'Dockerfile'
test_folder: docker
linters:
  # dockerfilelint
  - linter_name: dockerfilelint
    name: DOCKERFILE_DOCKERFILELINT
    linter_url: https://github.com/replicatedhq/dockerfilelint
    linter_rules_url: https://github.com/replicatedhq/dockerfilelint#checks-performed
    linter_rules_configuration_url: https://github.com/replicatedhq/dockerfilelint#configuring
    config_file_name: .dockerfilelintrc
    cli_config_arg_name: ""
    examples:
      - "dockerfilelint Dockerfile"
    install:
      npm:
        - dockerfilelint
  # Hadolint
  - linter_name: hadolint
    name: DOCKERFILE_HADOLINT
    linter_url: https://github.com/hadolint/hadolint
    linter_rules_url: https://github.com/hadolint/hadolint#rules
    linter_image_url: https://hadolint.github.io/hadolint/img/cat_container.png
    linter_rules_configuration_url: https://github.com/hadolint/hadolint#configure
    linter_rules_inline_disable_url: https://github.com/hadolint/hadolint#inline-ignores
    linter_megalinter_ref_url: https://github.com/hadolint/hadolint/blob/master/docs/INTEGRATION.md#mega-linter
    cli_config_arg_name: "--config"
    config_file_name: .hadolint.yml
    examples:
      - "hadolint Dockerfile"
      - "hadolint --config .hadolint.yml Dockerfile"
    install:
      dockerfile:
        - FROM hadolint/hadolint:latest-alpine as hadolint
        - COPY --from=hadolint /bin/hadolint /usr/bin/hadolint
    ide:
      atom:
        - name: linter-hadolint
          url: https://atom.io/packages/linter-hadolint
      vscode:
        - name: hadolint
          url: https://marketplace.visualstudio.com/items?itemName=exiasr.hadolint
