{
 "title": "MegaLinter - Top Rules & Files",
 "description": "Most frequent lint rules and most impacted files across repositories",
 "tags": [ "megalinter" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Metrics datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "Logs datasource", "query": "loki" },
   {
    "name": "repo",
    "label": "Repository",
    "query": {
     "query": "label_values(megalinter_run_lintersCount, gitRepoName)"
    }
   },
   {
    "name": "branch",
    "label": "Branch",
    "query": {
     "query": "label_values(megalinter_run_lintersCount{gitRepoName=~\"$repo\"}, gitBranchName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top rules across repositories (selected period)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum by (ruleId) (sum_over_time({source=\"MegaLinter\",recordType=\"rule\",gitRepoName=~\"$repo\",gitBranchName=~\"$branch\"} | json | unwrap occurrences [$__range])))"
    }
   ]
  },
  {
   "title": "Top files across repositories (selected period)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum by (file) (sum_over_time({source=\"MegaLinter\",recordType=\"file\",gitRepoName=~\"$repo\",gitBranchName=~\"$branch\"} | json | unwrap occurrences [$__range])))"
    }
   ]
  },
  {
   "title": "Rule hits by linter (selected period)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(15, sum by (linterKey) (sum_over_time({source=\"MegaLinter\",recordType=\"rule\",gitRepoName=~\"$repo\",gitBranchName=~\"$branch\"} | json | unwrap occurrences [$__range])))"
    }
   ]
  },
  {
   "title": "Errors by descriptor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by (descriptor) (megalinter_linter_run_numberErrorsFound{gitRepoName=~\"$repo\",gitBranchName=~\"$branch\"} > 0)",
     "legendFormat": "{{descriptor}}"
    }
   ]
  },
  {
   "title": "Rule hits trend",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (ruleId) (sum_over_time({source=\"MegaLinter\",recordType=\"rule\",gitRepoName=~\"$repo\",gitBranchName=~\"$branch\"} | json | unwrap occurrences [$__interval]))",
     "legendFormat": "{{ruleId}}"
    }
   ]
  },
  {
   "title": "Hotspot files (file x linter, selected period)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "topk(15, sum by (file, linterKey) (sum_over_time({source=\"MegaLinter\",recordType=\"file\",gitRepoName=~\"$repo\",gitBranchName=~\"$branch\"} | json | unwrap occurrences [$__range])))"
    }
   ]
  }
 ]
}