FROM hadolint/hadolint:v2.12.0-alpine as hadolint
FROM trufflesecurity/trufflehog:latest as trufflehog

##################
# Build wheel for megalinter python package
##################
FROM ghcr.io/astral-sh/uv:0.4.19 AS uv
FROM python:3.12.7-alpine3.20 AS build-ml-core
WORKDIR /
COPY pyproject.toml .
COPY --from=uv /uv /bin/uv
RUN --mount=type=cache,target=/root/.cache/uv \
     uv pip install --system -r pyproject.toml
COPY . .
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install --system .

FROM python:3.12-alpine

WORKDIR /

RUN apk add \
    bash \
    git \
    nodejs \
    npm

RUN wget --tries=5 -q -O - https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

COPY --link --from=hadolint /bin/hadolint /usr/bin/hadolint
COPY --link --from=trufflehog /usr/bin/trufflehog /usr/bin/

ENV MEGALINTER_FLAVOR=security

# Core MegaLinter
COPY --from=build-ml-core pyproject.toml README.md ./
COPY --from=build-ml-core megalinter /megalinter/
RUN --mount=type=cache,target=/root/.cache/uv,from=build-ml-core \
    --mount=from=uv,source=/uv,target=/bin/uv \
    uv pip install --system -e .

COPY megalinter/descriptors /megalinter-descriptors
COPY TEMPLATES /action/lib/.automation

# MegaLinter Server
COPY server /server
COPY server/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY logging.conf logging.conf
