FROM hadolint/hadolint:v2.12.0-alpine as hadolint
FROM trufflesecurity/trufflehog:latest as trufflehog

FROM python:3.12-alpine

WORKDIR /

RUN apk add \
    bash \
    git \
    nodejs \
    npm

RUN wget --tries=5 -q -O - https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

COPY --link --from=hadolint /bin/hadolint /usr/bin/hadolint
COPY --link --from=trufflehog /usr/bin/trufflehog /usr/bin/

ENV MEGALINTER_FLAVOR=security

# Core MegaLinter
RUN PYTHONDONTWRITEBYTECODE=1 pip3 install --no-cache-dir . \
    pip3 cache purge \
    && rm -rf /var/cache/apk/* \
    && find . \( -type f \( -iname \*.pyc -o -iname \*.pyo \) -o -type d -iname __pycache__ \) -delete

COPY megalinter/descriptors /megalinter-descriptors
COPY TEMPLATES /action/lib/.automation

# MegaLinter Server
COPY server /server
COPY server/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY logging.conf logging.conf
