---

#######################################
#######################################
## AsyncAPI and OpenAPI Linter rules ##
#######################################
#######################################

extends:
  - spectral:asyncapi
  - spectral:oas
