from setuptools import setup

setup(
    name="megalinter",
    version="0.1",
    description="Mega-Linter",
    url="http://github.com/megalinter/megalinter",
    author="Nicolas Vuillamy",
    author_email="nicolas.vuillamy@gmail.com",
    license="MIT",
    packages=["megalinter", "megalinter.linters", "megalinter.reporters"],
    install_requires=[
        "gitpython",
        "jsonschema",
        "jsonpickle",
        "multiprocessing_logging",
        "pychalk",
        "pygithub",
        "commentjson",
        "pytablewriter",
        "pytest-cov",
        "pytest-timeout",
        "pyyaml",
        "requests==2.24.0",
        "terminaltables",
        "webpreview",
        "yq",
        "importlib-metadata>=3.10",
        "mkdocs-material",
        "mdx_truly_sane_lists",
        "beautifulsoup4",
        "giturlparse",
    ],
    zip_safe=False,
)
