name: "DOC - Build and deploy - Beta"
on:
  push:
    branches:
      - main
      - features/doc-versioning
      - doc
    paths:
      - "**/build.py"
      - "docs/**"
      - "**.yml"
      - "**.md"
      - "**.json"

permissions: {}
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.repository == 'oxsecurity/megalinter'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: true
          fetch-depth: 0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: 3.14.6
      - run: pip install --upgrade -r .config/python/dev/requirements.txt
      - run: cd .automation && bash build_schemas_doc.sh && cd ..
      # - run: mkdocs gh-deploy --force
      - run: |
          git config --global user.name megalinter-bot
          git config --global user.email 129584137+megalinter-bot@users.noreply.github.com
      - run: mike deploy beta --push

 
