name: "DOC - Build and deploy - Beta"
on:
  push:
    branches:
      - main
      - features/doc-versioning
      - doc
    paths:
      - "**/build.py"
      - "docs/**"
      - "**.yml"
      - "**.md"
      - "**.json"

permissions: {}
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.repository == 'oxsecurity/megalinter'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.14.4
      - run: pip install --upgrade -r .config/python/dev/requirements.txt
      - run: cd .automation && bash build_schemas_doc.sh && cd ..
      # - run: mkdocs gh-deploy --force
      - run: |
          git config --global user.name megalinter-bot
          git config --global user.email 129584137+megalinter-bot@users.noreply.github.com
      - run: mike deploy beta --push

 
