---
#########################
#########################
## Deploy Docker Image Flavors ##
#########################
#########################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to main #
#######################################
name: "Build & Deploy - ALPHA Flavors"
on:
  push:
    branches:
      - "alpha"
    paths:
      - ".github/workflows/**"
      - "Dockerfile"
      - "flavors/**"
      - "megalinter/**"
      - "mega-linter-runner/**"
      - "server/**"
      - "**/linter-versions.json"
      - "TEMPLATES/**"
      - ".trivyignore"
      - "**/.sh"

###############
# Set the Job #
###############
permissions: {}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  build:
    # Name the Job
    name: Deploy Docker Image - ALPHA - Flavors
    # Set the agent to run on
    runs-on: ${{ matrix.os }}
    permissions:
      actions: write
      packages: write
      # Require writing security events to upload SARIF file to security tab
      security-events: write
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        os: [ubuntu-latest]
        # flavors-start
        flavor:
          [
            "ci_light",
            "cupcake",
            "documentation",
            "dotnet",
            "go",
            "java",
            "javascript",
            "php",
            "python",
            "ruby",
            "rust",
            "salesforce",
            "security",
            "swift",
            "terraform",
          ]
# flavors-end
    # Only run this on the main repo
    if: github.repository == 'oxsecurity/megalinter' && !contains(github.event.head_commit.message, 'skip deploy')
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        run: echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "${GITHUB_ENV}"

      - name: Build Image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: .
          file: flavors/${{ matrix.flavor }}/Dockerfile
          platforms: linux/amd64
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=alpha
          load: false
          push: true
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: |
            ghcr.io/oxsecurity/megalinter-${{ matrix.flavor }}:alpha
          cache-from: type=gha,scope=beta-flavor-${{ matrix.flavor }}-linux/amd64

      # - name: Build Worker Image
      #   uses: docker/build-push-action@v7
      #   with:
      #     context: .
      #     file: Dockerfile-worker
      #     platforms: linux/amd64
      #     build-args: |
      #       MEGALINTER_BASE_IMAGE=ghcr.io/oxsecurity/megalinter-${{ matrix.flavor }}:alpha
      #       BUILD_DATE=${{ env.BUILD_DATE }}
      #       BUILD_REVISION=${{ github.sha }}
      #       BUILD_VERSION=alpha
      #     load: false
      #     push: true
      #     secrets: |
      #       GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
      #     tags: |
      #       ghcr.io/oxsecurity/megalinter-worker-${{ matrix.flavor }}:alpha

      ##############################################
      # Check Docker image security with Trivy #
      ##############################################
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ghcr.io/oxsecurity/megalinter-${{ matrix.flavor }}:alpha
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          scanners: vuln
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: 10m0s
        env:
            ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Run OSV-Scanner vulnerability scanner
      #   uses: google/osv-scanner-action/osv-scanner-action@v2.3.5
      #   with:
      #     scan-args: |-
      #       --docker ghcr.io/oxsecurity/megalinter-${{ matrix.flavor }}:alpha
