---
#########################
#########################
## Deploy Docker Image ##
#########################
#########################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to main #
#######################################
name: "Build & Deploy - DEV"
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - .github/CONTRIBUTING.md
      - CHANGELOG.md
      - README.md
      - .github/workflows/slash-command-dispatch.yml
      - .github/workflows/help-command.yml
      - .github/workflows/build-command.yml
  pull_request:

###############
# Set the Job #
###############
permissions: {}

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    # Name the Job
    name: Tests + Deploy Docker Image - DEV
    # Set the agent to run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Require writing security events to upload SARIF file to security tab
      security-events: write
    # Prevent duplicate run from happening when a forked push is committed
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, 'skip deploy')
    # Set max build time for the job
    timeout-minutes: 120
    ##################
    # Load all steps #
    ##################
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Free Disk space
        shell: bash
        run: |
          sudo rm -rf /usr/local/lib/android  # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /opt/hostedtoolcache/CodeQL # large cache
          sudo rm -rf /opt/hostedtoolcache/go # Go toolcache

      - name: Docker Metadata action
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        id: meta
        with:
          images: |
            ${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      ###################################
      # Build image locally for testing #
      ###################################
      - name: Build MegaLinter Docker Image (quick)
        if: ${{ contains(github.event.head_commit.message, 'quick build') }}
        id: docker_build_quick
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: .
          file: Dockerfile-quick
          platforms: linux/amd64
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            BUILD_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            BUILD_REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
            MEGA_LINTER_BASE_IMAGE="oxsecurity/megalinter:beta"
          load: true
          push: false
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
        timeout-minutes: 90

      #######################################
      # Build image (full for forked repos) #
      #######################################
      - name: Build MegaLinter Docker Image (full from forks)
        if: |
          (
          (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) ||
          (github.event_name == 'push' && github.repository != 'oxsecurity/megalinter')
          )
          &&
          !contains(github.event.head_commit.message, 'quick build')
        id: docker_build
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            BUILD_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            BUILD_REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          load: true
          push: false
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
        timeout-minutes: 90

      ####################################
      # Build image (full for main repo) #
      ####################################
      - name: Build MegaLinter Docker Image (full from main repo) & push
        if: |
          (
          (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) ||
          (github.event_name == 'push' && github.repository == 'oxsecurity/megalinter')
          )
          &&
          !contains(github.event.head_commit.message, 'quick build')
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            BUILD_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            BUILD_REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          load: true
          push: false
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Clean docker buildx cache
        run: docker buildx prune --force

      #####################################
      # Run Linter test cases #
      #####################################
      - name: Run Test Cases
        shell: bash
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          GH_REPOSITORY: ${{ github.repository }}
          HEAD_REF: ${{ github.head_ref }}
          REF_NAME: ${{ github.ref_name }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          DOCKER_IMAGE: ${{ fromJson(steps.meta.outputs.json).tags[0] }}
          GH_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GITHUB_REPOSITORY=$([ "$EVENT_NAME" == "pull_request" ] && echo "$PR_HEAD_REPO" || echo "$GH_REPOSITORY")
          GITHUB_BRANCH=$([ "$EVENT_NAME" == "pull_request" ] && echo "$HEAD_REF" || echo "$REF_NAME")

          CI_ENV="$(bash <(curl -s https://codecov.io/env)) -e GITHUB_ACTIONS"
          export CI_ENV
          TEST_KEYWORDS_TO_USE=""
          if [[ "${COMMIT_MSG}" == *"TEST_KEYWORDS="* ]]; then
            TEST_KEYWORDS_TO_USE=${COMMIT_MSG#*TEST_KEYWORDS=}
            echo "Run only tests with keywords ${TEST_KEYWORDS_TO_USE}"
            if [[ "${TEST_KEYWORDS_TO_USE}" =~ $'\r' ]]; then
                echo "Problem while parsing test keywords: switch back to all tests"
                TEST_KEYWORDS_TO_USE=""
            fi
          fi
          docker image ls
          # shellcheck disable=SC2086
          docker run $CI_ENV -e TEST_CASE_RUN=true -e OUTPUT_FORMAT=text -e OUTPUT_FOLDER="${GH_SHA}" -e OUTPUT_DETAIL=detailed -e GITHUB_SHA="${GH_SHA}" -e GITHUB_REPOSITORY="${GITHUB_REPOSITORY}" -e GITHUB_BRANCH="${GITHUB_BRANCH}" -e GITHUB_TOKEN="${GITHUB_TOKEN}" -e TEST_KEYWORDS="${TEST_KEYWORDS_TO_USE}" -e MEGALINTER_VOLUME_ROOT="${GITHUB_WORKSPACE}" -v "/var/run/docker.sock:/var/run/docker.sock:rw" -v "${GITHUB_WORKSPACE}:/tmp/lint" "${DOCKER_IMAGE}"
        timeout-minutes: 120

      #####################################
      # Run Linter against ALL code base  #
      #####################################
      - name: Run against all code base
        if: "!contains(github.event.head_commit.message, 'quick build')"
        shell: bash
        env:
          DOCKER_IMAGE: ${{ fromJson(steps.meta.outputs.json).tags[0] }}
          GH_REPOSITORY: ${{ github.repository }}
          GH_SHA: ${{ github.sha }}
          GH_TOKEN_VALUE: ${{ github.token }}
          GH_RUN_ID: ${{ github.run_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker run -e GITHUB_REPOSITORY="${GH_REPOSITORY}" -e GITHUB_SHA="${GH_SHA}" -e GITHUB_TOKEN="${GH_TOKEN_VALUE}" -e GITHUB_RUN_ID="${GH_RUN_ID}" -e GITHUB_TOKEN="${GITHUB_TOKEN}" -v "/var/run/docker.sock:/var/run/docker.sock:rw" -v "${GITHUB_WORKSPACE}:/tmp/lint" "${DOCKER_IMAGE}"
        timeout-minutes: 15

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: success() || failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: MegaLinter reports
          include-hidden-files: "true"
          path: |
            megalinter-reports
            mega-linter.log
            linter-helps.json
            linter-versions.json

      - name: debug
        if: success() || failure()
        run: echo "${STEPS_DOCKER_BUILD_OUTCOME}"
        env:
          STEPS_DOCKER_BUILD_OUTCOME: ${{ steps.docker_build.outcome }}

      # Clean disk space
      - name: Clear disk space
        run: |
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo swapoff -a || true
          sudo rm -f /swapfile || true
          sudo apt clean || true

      # Test mega-linter-runner with newly created image
      - name: Setup Node
        if: steps.docker_build.outcome == 'success' && !contains(github.event.head_commit.message, 'quick build')
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.x"
      - name: Install NPM dependencies
        if: steps.docker_build.outcome == 'success' && !contains(github.event.head_commit.message, 'quick build')
        run: cd mega-linter-runner && yarn install --frozen-lockfile && npm link
      - name: Run mega-linter-runner tests
        if: steps.docker_build.outcome == 'success' && !contains(github.event.head_commit.message, 'quick build')
        env:
          MEGALINTER_RELEASE: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          MEGALINTER_IMAGE: ${{ fromJson(steps.meta.outputs.json).tags[0] }}
        run: cd mega-linter-runner && MEGALINTER_RELEASE="${MEGALINTER_RELEASE}" MEGALINTER_IMAGE="${MEGALINTER_IMAGE}" MEGALINTER_NO_DOCKER_PULL=true npm run test

      # - name: free disk space
      #   run: |
      #     sudo swapoff -a || true
      #     sudo rm -f /swapfile || true
      #     sudo apt clean || true

      ##############################################
      # Check Docker image security with Trivy #
      ##############################################

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: "${{ fromJson(steps.meta.outputs.json).tags[0]}}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          scanners: vuln
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: 15m0s

      # - name: Run OSV-Scanner vulnerability scanner
      #   uses: google/osv-scanner-action/osv-scanner-action@v2.3.5
      #   with:
      #     scan-args: |-
      #       --docker ${{ fromJson(steps.meta.outputs.json).tags[0] }}
