name: "Check MkDocs generation"
on:
  push:
    paths:
      - "**/mkdocs.yml"
  pull_request:
    paths:
      - "**/mkdocs.yml"

permissions: {}
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  test-doc-gen:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: 3.14.6
      - run: pip install --upgrade -r .config/python/dev/requirements.txt
      - run: cd .automation && bash build_schemas_doc.sh && cd ..
      - run: mkdocs build

 
