name: "Check MkDocs generation"
on:
  push:
    paths:
      - "**/mkdocs.yml"
  pull_request:
    paths:
      - "**/mkdocs.yml"

permissions: {}
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  test-doc-gen:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.14.6
      - run: pip install --upgrade -r .config/python/dev/requirements.txt
      - run: cd .automation && bash build_schemas_doc.sh && cd ..
      - run: mkdocs build

 
